#macro ENTITIES global.entities
#macro PROJECTILES global.projectileManager
#macro ENEMIES global.EnemyManager
#macro SOUND global.soundManager
#macro GAME global.game
#macro WORLD global.world
#macro PARTICLES global.particleSystem
#macro VBUTTON global.vbutton
#macro LOG global.logger
#macro GAME_W 320
#macro GAME_H 240
#macro CURRENT_FRAME global.game.__current_frame
#macro PLAYER_SPRITE global.availible_characters[global.character_index].image_folder